// Base Influencer Tweet Training Data
// Fresh data from Base chain influencers + new influencers

export function getTrainingData() {
  const tweets = [
    "The two best accounts for base trench alpha are @rbthreek @mathburn666 You'd 10x your portfolio following their calls.",
    "woke up to this. am i living in simulation? chat, is this real? broski wasnt kidding when he asked for my addy @Saxenasaheb",
    "ETH just broke $3900 You're not bullish enough on @base.",
    "Been posting consistently on X since last 2 months > No rewards Posted on @baseapp for 3 days > INR 4300/- I'm moving full time from X-Gram to Base-Zora and bringing all my friends with me.",
    "It's a tough world out there Make it easy basedfellowship(.)com @BasedIndia @callusfbi",
    "Today I'm grateful to be long @base and the entire Base ecosystem",
    "If you're new to @base here are some apps I recommend using @zora @cooprecsmusic @noicedotso @farcaster_xyz @rodeodotclub @clankeronbase @bankrbot @interfacedapp @BrackyHQ @higheronchain @podsdotmedia @wearehume @bpdotfun Way way more too - this is the tip of the iceberg",
    "Finally on the base app! Thanks @RajansheeS @callusfbi for the invite. Drop your handles, lets get based!",
    "Cooking @Saxenasaheb @NikhilEth @teamdotapk",
    "Hearing from the grapevine Projects are full porting over to @base in preparation for @baseapp going mainstream",
    "One thing I've learned building @Kuriorg solo—there's always one more tweak to the UI/UX. And it's easy to get stuck in the loop, chasing the high of building instead of shipping.",
    "First version of the Farcaster mini-app is about to done. Feels good to see ideas turning into code. Just a few iterations away from making it bulletproof. @Saxenasaheb @NikhilEth @Divyansh_S28 let's ship something dope.",
    "My trading strategy this cycle: 1) Find and support mini app builders on Base 2) If I like what they're building, buy the token Ex. $NOICE 3) Discover creators on Zora → buy their creator coins 4) Spot memers on Farcaster/BaseApp → buy their memes Simple: find conviction",
    "more football coming to @base",
    "welcome @jakehaener10 to @baseapp",
    "need more degen traders on @baseapp want in? I'll personally onboard you drop your wallet",
    "everyone realizing that social capital and financial capital are all just capital and the best form of capital to realize this might just be posting on this internet thing we spend our lives on so yes ofc the social networks of the future will be the capital markets of the future",
    "I believe Base Pay will be one of the breakthrough blockchain developer products like privy, wagmi, etc It has that rare mix of simple UX with great DevX. It's literally one line: pay(amount, address) No wallet connection, no 3rd party framework needed",
    "a new day one",
    "here's a few of the folks going. with more confirming each day. going to be next level",
    "Jacob says more coins launched on Zora yesterday than all Solana launchpads combined \"2M users have signed into Zora in the last month, 54k coins were deployed yesterday and over the weekend we did $63M in volume\"",
    "Are you based? @base @baseapp",
    "the real and inevitable unlock is using the \"value\" you've accrued as purchasing power. > post content > number in your wallet goes up > trade a lil bit of that number for a coffee and doing it without converting any coin or any currency.",
    "Your content. Your value. Your upside. Post it on the Base app.",
    "CREATE • ON • BASE •",
    "Zora is building a creator-first on-chain economy, where: • Creators earn from tokenized posts and profile coins, not just NFTs. • Growth accelerated since Zora moved to @base @jessepollak , a mature chain full of passionate builders. • Protocol fees and revenue are growing.",
    "STILL DAY ONE",
    "Your content has value.",
    "gm to the memecoin and NFT and content coin enthusiasts",
    "Believe in creators.",
    "if you are someone who loves NFTs and hates content coins: a content coin is just a 1/1 NFT that's fractionalized so more people can own it.",
    "buy some of this post NFT that I fractionalized so anyone can own as much or as little as they want",
    "$FXH trending in base app",
    "Trending now in the @baseapp",
    "thanks to everyone for the feedback and sharing the Wallet Sweeper post! here's some behind the scenes play-by-play of how it went from idea at 10:43am to shipped at 10:35pm while I spent the day seeing Superman & grabbing dinner with my dad",
    "ICYMI a ton of new creators from @samirchaudry to @GinoTheGhost are now using @zora from youtubers to music artists, creators are joining the @base ecosystem and bringing the creator economy onchain",
    "It's @base season",
    "These are some of the creator niches I'd love to see more of on @zora. I think there's real potential here, and real money for those making fire content. Fitness / Bodybuilding → Gym clips, transformations, daily discipline. Beauty / Skincare → Routines, product drops",
    "Wild that people resent the idea of tokenizing and owning their own content. The alternative? Get nothing while platforms sell your work for billies. It's pure Stockholm syndrome.",
    "Zora ($346k) flipped Pump ($187k) in daily revenue yesterday, but still trails the category leader Bonk ($1m)",
    "Why EIP-5792 is the Midas touch for Mini Apps EIP-5792 is becoming the golden standard for Mini Apps on the @baseapp . Mini Apps live or die by their first impression - when someone discovers your app in a social feed, you have seconds to hook them.",
    "Having fun on @baseapp? Building mini apps is even more fun Frens have been sharing screenshots of their SnackyCat high scores , so I updated the game to learn about Sign in with @base. Now you can see everyone's high scores and share + coin your SnackyCat moment on TBA",
    "Creators love @zora. @zora ? it's kinda dope.",
    "My story is I started posting + reposting on @zora like I would on @instagram or @tumblr + this happened. 20 years of using social media: $0 A few months of Zora: $2,000 That's the whole fucking story.",
    "creator coins are awesome. no reason to dump on your fans - the people that helped get you there in the first place. that's part of why we built flaunch <3",
    "content everywhere is valuable creators everywhere should be valued",
    "I've been creating online for over a decade. Posting every day. Memes, videos, photography. Pouring time and energy into things I cared about. Never really got paid for it. Not in any way that felt fair or real. Just platforms and algorithms benefiting from my creativity.",
    "My main job brought in just $1.5K–$1.7K/month. I even earned money just from posting on @zora, and that meant so much to my life. We create to connect — not just to catch trends. Forever grateful Thank you @base @zora @jessepollak @js_horne & everyone supporting",
    "I didn't keep all the revenue but my creator coin on @flaunchgg has earned $92,000 in ETH (not NOBI) and I've never sold a coin. Burned like 10% of the supply as well",
    "Check out this mega thread where I've compiled all my Web3 marketing tweets from 2023 If you like this tweet, I'll ensure you receive a discount on the mint of my meme coin during this bull season. Quote tweets will be considered as a multiplier.",
    "Base has the best GTM for creators and early-stage builders at the moment. For builders - Participate in various Base fellowships/accelerators/ programs across the globe to validate the idea and get the initial push - Ship mini apps - Distribute through Farcaster and the Base",
    "I yap about products, projects, and ecosystems that don't have mindshare leaderboards.",
    "The base trifecta I am in love with: The Base App Zora Farcaster The world is getting onchain",
    "where are you?",
    "A scrappy list of tips for those who just got into crypto: - Read about: money, BTC, ETH, blockchain tech, DeFi (read 'how to DeFi' book) - Build onchain reputation. Use products. Increase your onchain score. (check at: onchainscore dot xyz) - Strive to earn your first crypto",
    "Mint your creator coin on @zora Also, use Zora as Instagram. Distribute your creator coin on @farcaster using @noicedotso. Also, use Farcaster to build communities through a channel. Trade and discover more of this on the @baseapp. Also, use the base app as your onchain",
    "Gradually gearing up to become the unofficial BD of the @baseapp",
    "Based Punks are good people. CC: @Saxenasaheb Also, shutout to OG @314yush Latest entry: @shirollsasaki",
    "If I ever do a crypto marketing course, it will be free. Why? Because I absolutely despise and detest all these paid marketing courses/certifications that are popping up. Also, to prove that you don't need to be a part of some pretentious growth communities to learn.",
    "Turns out I am not a CMO",
    "Agentic era and deAI are taking over your TL - WE KNOWW But do you know what all is possible for you in the era of AI agents? Time to find out with @okto_web3 @BasedIndia @HeyElsaAI @CredShields @QuillAI_Network Meet our powerhouse lineup: @cyberboyIndia @bigrkg @kunalvg",
    "answering the most popular questions about coining and trading on @baseapp : how do I know if a post is coined? –scroll through the feed and look for the icon with numbers — that's the market cap, which means the post is coined how do I buy a coin from the feed?",
    "where can you check? Here:",
    "mint is working fine now",
    "It's been 8 months now and Ethereum is still inflationary.",
    "This mint isn’t ending in 6 hours; it’s 6 days. Sorry frens I didn’t notice :)",
    "Bybit CEO is asking for help",
    "Funds Are Safe ?",
    "Why is an Ethereum L2 selling their useless governance tokens to the public?",
    "would you work full time in crypto for $1M per year?",
    "ocean view >",
    "what coins interest you at the moment?",
    "goodnight chat",
    "BonkFun powered by Raydium did ~21x more volume than PumpFun in the last 24 hours",
    "goodnight chat",
    "monad is launching on september 30?",
    "pump fun breaks record lows",
    "$PENGU is the best $SOL beta",
    "Learn more here:",
    "He's at it again",
    "Learn more:",
    "App.js gist:",
    "Great example of how new social contexts (coined content) lead to new social experiences (swipe through content to Buy or Bye)",
    "Can't believe this was only 3 years ago :)",
    "Base Pay is built on open standards!",
    "Happy July 4th to my American frens",
    "A call for Base Buildooors",
    "Base est pour tout le monde",
    "Why are people lining up to take a photo with EthCC banners?",
    "i love announcements of the announcement",
    "we’ve entered the danger area",
    "i hate monad",
    "you might want to hold a chog mystery chest for monad mainnet.",
    "I’m never doing drunk interviews again",
    "we don’t play by the rules",
    "i’m your closest source for every insider’s information on monad (real)",
    "time to send out invitations to my cabal",
    "can i get a hi today?",
    "the most punchable PFP in the world rn.",
    "there was actually so much hidden alpha despite the noise",
    "monad owes me a big fat airdrop just for showing up every day.",
    "or a kiss like this one",
    "keep looking for the key",
    "are we still bullish on monad??",
    "im out of thoughts to tweet",
    "peak mountain life",
    "spotify wrapped. but better",
    "bro is eating up space. time to clear nodes and targets",
    "how to write better ?",
    "is zed + vim gud?",
    "the devil’s in the basics.",
    "what's one thing you added to your lifestyle that 10x'd your dev skills?",
    "blue tick is gone since i changed my pfp",
    "arch boys are just waiting for a macbook",
    "missed this desk for the last 15 days. feels good to be back",
    "third-party railway booking apps wouldn't even exist if the official IRCTC site had decent UX",
    "HJKL is enough",
    "anyone cooking killer apps for the solana mobile hackathon ?",
    "bought solana mobile ;)",
    "im done with rust",
    "finally found someone who matches my emotional intelligence",
    "wasting my time wisely",
    "proof of thorfinn",
    "gm. what y’all doin’ today?",
    "learn vim macros",
    "You can learn a lot about an engineer by noticing how they react when someone else solves a problem that they were stuck on for a while.",
    "so eth isn’t a stablecoin anymore?",
    "how imagining what your twenties would be like felt as a kid",
    "brother what kind of softwares are y’all making??",
    "backend developers here’s a great opportunity for you!!!",
    "costs me my mental health tbh",
    "i really love designing database schemas",
    "happy “INDIA HAVE PULLED OFF A HEIST TO BECOME THE 2024 ICC MEN'S T20 WORLD CUP CHAMPIONS!” day to everyone",
    "unpopular opinion: sacred games was hyped more than required because it was the first indian web series",
    "what i describe as a “good day”",
    "weekend was pretty",
    "being strong is fun until you realize no one checks if you’re okay anymore.",
    "some more from yesterday",
    "what’s new?",
    "meanwhile people in the eastern part of the world",
    "Hence always choose AR",
    "Finally we're at $800Mn",
    "Its time for Cabbage Yaps",
    "A random road in Kerala",
    "US didn’t provide the OTP & here we have it at Kerala",
    "Can’t keep it sealed",
    "Proof of Monke",
    "In our OG group with my OG frens",
    "Chonkyyyyyy",
    "Finally crashed",
    "100k in web3",
    "Can I get one follower",
    "I acknowledge that I am a scammer",
    "Got an interesting box this morning",
    "Who all are signing up for REMILIO ACADEMY FOR GIFTED YOUNG TRILLIONARIES",
    "Distribution >>>Advancement",
    "Forever grateful for such high vibe experiences!",
    "You got it right",
    "Breathe if I’m your favourite",
    "Officer of love",
    "Invite code to join your Morning laughter classes: BAHAHA8080",
    "My Dream WFH setup",
    "I swear the garden smelled like alot of flowers <3",
    "My X fam should see this first",
    "Will CT forgive me if I say GOOD MORNING instead of GM?",
    "What!!! Gamers are crazy fr",
    "Feel free to follow me on Farcaster:",
    "Avoid these mistakes when growing an airdrop account on CT:",
    "This was a main reason why I skipped Sonic:",
    "Feel free to follow me on Farcaster:",
    "Avoid these mistakes when growing an airdrop account on CT:",
    "Avoid these mistakes when growing an airdrop account on CT:",
    "The complete framework I'm using to compound long-term wealth on CT:",
    "Why I skipped Sonic:",
    "Feel free to follow me on Zora:",
    "Revealing my full HyperEVM strategy:",
    "How the InfoFi meta will change:",
    "Stop wasting time on airdrops with poor ROI:",
    "everyone realizing that social capital and financial capital are all just capital and the best form of capital to realize this might just be posting on this internet thing we spend our lives on so yes ofc the social networks of the future will be the capital markets of the future",
    "a new day one",
    "if you’re dismissing work based on its token standard you’re probably missing the point",
    "CREATE • ON • BASE •",
    "read our full thinking",
    "STILL DAY ONE",
    "Your content has value.",
    "gm to the memecoin and NFT and content coin enthusiasts",
    "Believe in creators.",
    "if you are someone who loves NFTs and hates content coins: a content coin is just a 1/1 NFT that's fractionalized so more people can own it.",
    "buy some of this post NFT that I fractionalized so anyone can own as much or as little as they want",
    "$FXH trending in base app",
    "creator coins on solana have intrinsic value",
    "Turns out I am not a CMO",
    "Removed CMO from my bio.",
    "I believed in somETHing",
    "Marketer and dev agreeing on the feature launch date.",
    "I had my weak moments. But I always believed in somETHing.",
    "Pumped for TBA",
    "Be everything but not a simp.",
    "I want to watch ETH in 4K.",
    "Whts happening bro",
    "Always you also special yash bro",
    "Supreme leader issues",
    "Supreme leader -10000 social credits",
    "Sleep is overrated.",
    "fuck it we ball",
    "Can i get into athena too??",
    "Pow please shishu bhai?",
    "I lub design Gruz more than dev gruz",
    "need mini militia on baseapp",
    "I’d love priyanshu to not just chug redbull only during the hh :D",
    "JavaScript is what we all started with",
    "Yes ayush bhai",
    "Chad account chad community",
    "Going super saiyan mode then",
    "I wish I was a part of this",
    "!!!!!!!!!!!!!!! this is BASED",
    "best app = best juice = best team",
    "baseshake around the world",
    "my first in-n-out",
    "communication is key in our team lol",
    "TBA: Trade Based Assets",
    "TBA LA 2025",
    "crazy times at the dream job.",
    "Base is for everyone is trending on TBA",
    "I'M ALL IN TBA",
    "4 Am club??",
    "4 Am club??",
    "10/10 kyu nhi ho rha??",
    "4 Am club for W",
    "Only symmetry i like",
    "aur kis kis ko ye galtfehmi hai??",
    "4 Am club??",
    "My personal rule is to never take a developer in a team who’s worked with light theme",
    "if u still can't understand NGMI.",
    "satyam bhai ko legal notice bhej du?? what's ur thought chat???",
    "Sometimes it’s worth trading earnings for learnings(learn about web3)",
    "Satya Nadella to his employees this week-",
    "Every time my parents ask me about my career choices:",
    "Tell me you’ve moved to Bangalore without telling me you’ve moved to bangalore.",
    "This man will go down in history books as the guy who dedicated his life to bringing the world onchain.",
    "The hack to being good at BD is being a good person.",
    "Wake me up when 2023 ends:",
    "Idea Town w/ Bhavya",
    "where can you check? Here:",
    "mint is working fine now",
    "It's been 8 months now and Ethereum is still inflationary.",
    "This mint isn’t ending in 6 hours; it’s 6 days. Sorry frens I didn’t notice :)",
    "Bybit CEO is asking for help",
    "Funds Are Safe ?",
    "Why is an Ethereum L2 selling their useless governance tokens to the public?",
    "would you work full time in crypto for $1M per year?",
    "ocean view >",
    "what coins interest you at the moment?",
    "goodnight chat",
    "BonkFun powered by Raydium did ~21x more volume than PumpFun in the last 24 hours",
    "goodnight chat",
    "monad is launching on september 30?",
    "pump fun breaks record lows",
    "$PENGU is the best $SOL beta",
    "Learn more here:",
    "He's at it again",
    "Learn more:",
    "App.js gist:",
    "Great example of how new social contexts (coined content) lead to new social experiences (swipe through content to Buy or Bye)",
    "Can't believe this was only 3 years ago :)",
    "Base Pay is built on open standards!",
    "Happy July 4th to my American frens",
    "A call for Base Buildooors",
    "Base est pour tout le monde",
    "Why are people lining up to take a photo with EthCC banners?",
    "i love announcements of the announcement",
    "we’ve entered the danger area",
    "i hate monad",
    "you might want to hold a chog mystery chest for monad mainnet.",
    "I’m never doing drunk interviews again",
    "we don’t play by the rules",
    "i’m your closest source for every insider’s information on monad (real)",
    "time to send out invitations to my cabal",
    "can i get a hi today?",
    "the most punchable PFP in the world rn.",
    "there was actually so much hidden alpha despite the noise",
    "monad owes me a big fat airdrop just for showing up every day.",
    "or a kiss like this one",
    "keep looking for the key",
    "are we still bullish on monad??",
    "im out of thoughts to tweet",
    "peak mountain life",
    "spotify wrapped. but better",
    "bro is eating up space. time to clear nodes and targets",
    "how to write better ?",
    "is zed + vim gud?",
    "the devil’s in the basics.",
    "what's one thing you added to your lifestyle that 10x'd your dev skills?",
    "blue tick is gone since i changed my pfp",
    "arch boys are just waiting for a macbook",
    "missed this desk for the last 15 days. feels good to be back",
    "third-party railway booking apps wouldn't even exist if the official IRCTC site had decent UX",
    "HJKL is enough",
    "anyone cooking killer apps for the solana mobile hackathon ?",
    "bought solana mobile ;)",
    "im done with rust",
    "finally found someone who matches my emotional intelligence",
    "wasting my time wisely",
    "proof of thorfinn",
    "gm. what y’all doin’ today?",
    "learn vim macros",
    "You can learn a lot about an engineer by noticing how they react when someone else solves a problem that they were stuck on for a while.",
    "so eth isn’t a stablecoin anymore?",
    "how imagining what your twenties would be like felt as a kid",
    "brother what kind of softwares are y’all making??",
    "backend developers here’s a great opportunity for you!!!",
    "costs me my mental health tbh",
    "i really love designing database schemas",
    "happy “INDIA HAVE PULLED OFF A HEIST TO BECOME THE 2024 ICC MEN'S T20 WORLD CUP CHAMPIONS!” day to everyone",
    "unpopular opinion: sacred games was hyped more than required because it was the first indian web series",
    "what i describe as a “good day”",
    "weekend was pretty",
    "being strong is fun until you realize no one checks if you’re okay anymore.",
    "some more from yesterday",
    "what’s new?",
    "meanwhile people in the eastern part of the world",
    "Hence always choose AR",
    "Finally we're at $800Mn",
    "Its time for Cabbage Yaps",
    "A random road in Kerala",
    "US didn’t provide the OTP & here we have it at Kerala",
    "Can’t keep it sealed",
    "Proof of Monke",
    "In our OG group with my OG frens",
    "Chonkyyyyyy",
    "Finally crashed",
    "100k in web3",
    "Can I get one follower",
    "I acknowledge that I am a scammer",
    "Got an interesting box this morning",
    "Who all are signing up for REMILIO ACADEMY FOR GIFTED YOUNG TRILLIONARIES",
    "Distribution >>>Advancement",
    "Forever grateful for such high vibe experiences!",
    "You got it right",
    "Breathe if I’m your favourite",
    "Officer of love",
    "Invite code to join your Morning laughter classes: BAHAHA8080",
    "My Dream WFH setup",
    "I swear the garden smelled like alot of flowers <3",
    "My X fam should see this first",
    "Will CT forgive me if I say GOOD MORNING instead of GM?",
    "What!!! Gamers are crazy fr",
    "Feel free to follow me on Farcaster:",
    "Avoid these mistakes when growing an airdrop account on CT:",
    "This was a main reason why I skipped Sonic:",
    "Feel free to follow me on Farcaster:",
    "Avoid these mistakes when growing an airdrop account on CT:",
    "Avoid these mistakes when growing an airdrop account on CT:",
    "The complete framework I'm using to compound long-term wealth on CT:",
    "Why I skipped Sonic:",
    "Feel free to follow me on Zora:",
    "Revealing my full HyperEVM strategy:",
    "How the InfoFi meta will change:",
    "Stop wasting time on airdrops with poor ROI:",
    "everyone realizing that social capital and financial capital are all just capital and the best form of capital to realize this might just be posting on this internet thing we spend our lives on so yes ofc the social networks of the future will be the capital markets of the future",
    "a new day one",
    "if you’re dismissing work based on its token standard you’re probably missing the point",
    "CREATE • ON • BASE •",
    "read our full thinking",
    "STILL DAY ONE",
    "Your content has value.",
    "gm to the memecoin and NFT and content coin enthusiasts",
    "Believe in creators.",
    "if you are someone who loves NFTs and hates content coins: a content coin is just a 1/1 NFT that's fractionalized so more people can own it.",
    "buy some of this post NFT that I fractionalized so anyone can own as much or as little as they want",
    "$FXH trending in base app",
    "creator coins on solana have intrinsic value",
    "Turns out I am not a CMO",
    "Removed CMO from my bio.",
    "I believed in somETHing",
    "Marketer and dev agreeing on the feature launch date.",
    "I had my weak moments. But I always believed in somETHing.",
    "Pumped for TBA",
    "Be everything but not a simp.",
    "I want to watch ETH in 4K.",
    "Whts happening bro",
    "Always you also special yash bro",
    "Supreme leader issues",
    "Supreme leader -10000 social credits",
    "Sleep is overrated.",
    "fuck it we ball",
    "Can i get into athena too??",
    "Pow please shishu bhai?",
    "I lub design Gruz more than dev gruz",
    "need mini militia on baseapp",
    "I’d love priyanshu to not just chug redbull only during the hh :D",
    "JavaScript is what we all started with",
    "Yes ayush bhai",
    "Chad account chad community",
    "Going super saiyan mode then",
    "I wish I was a part of this",
    "!!!!!!!!!!!!!!! this is BASED",
    "best app = best juice = best team",
    "baseshake around the world",
    "my first in-n-out",
    "communication is key in our team lol",
    "TBA: Trade Based Assets",
    "TBA LA 2025",
    "crazy times at the dream job.",
    "Base is for everyone is trending on TBA",
    "I'M ALL IN TBA",
    "4 Am club??",
    "4 Am club??",
    "10/10 kyu nhi ho rha??",
    "4 Am club for W",
    "Only symmetry i like",
    "aur kis kis ko ye galtfehmi hai??",
    "4 Am club??",
    "My personal rule is to never take a developer in a team who’s worked with light theme",
    "if u still can't understand NGMI.",
    "satyam bhai ko legal notice bhej du?? what's ur thought chat???",
    "Sometimes it’s worth trading earnings for learnings(learn about web3)",
    "Satya Nadella to his employees this week-",
    "Every time my parents ask me about my career choices:",
    "Tell me you’ve moved to Bangalore without telling me you’ve moved to bangalore.",
    "This man will go down in history books as the guy who dedicated his life to bringing the world onchain.",
    "The hack to being good at BD is being a good person.",
    "Wake me up when 2023 ends:",
    "Idea Town w/ Bhavya",];

  return {
    tweets,
    totalCount: tweets.length,
    source: "Base chain influencers",
    scrapedAt: new Date().toISOString()
  };
}

export function extractAllTweetContent(): string[] {
  return getTrainingData().tweets;
}

export function getTweetsByStyle(style: string): string[] {
  // For now, return all tweets for any style
  // This can be enhanced later with style-specific filtering
  return getTrainingData().tweets;
} 